name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs: 
  backend:
    name: Backend build & Tests & Vulnarability-scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd backend
          npm install
          
      - name: Run Tests
        run: |
            cd backend
            npm test
      - name: Vulnarability-scanning
        run: |
             cd backend
             npm audit --audit-level=high
  frontend:
    name: Frontend Build & Tests & Vulnarability-scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Build
        run: |
          cd frontend
          npm run build

      - name: Vulnarability-scanning
        run: |
             cd frontend
             npm audit --audit-level=high
             npm audit fix --force

  trivy-scan:
    name: Scan Docker Image with Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

   
