name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  backend:
      name: Backend Tests
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v4 
        - name: Use Node.js
          uses: actions/setup-node@v4
        - name: Install dependencies
          run:
           cd backend
           npm install
        - name: npm build
          run: npm run build --if-present

